### ISSUE TITLE
LandsAddon - don't work on new versions of Lands plugin

### ISSUE THREAD

**Issue by VacBanYT** [InsightsPlugin/Insights#186] opened 2022-12-10 14:32 UTC
`[15:31:16 ERROR]: Could not pass event BlockPistonRetractEvent to Insights v6.13.0
java.lang.NoSuchMethodError: 'org.bukkit.World me.angeschossen.lands.api.land.ChunkCoordinate.getWorld()'
        at dev.frankheijden.insights.addons.lands.LandsAddon$LandsRegion.toChunkParts(LandsAddon.java:106) ~[?:?]
        at dev.frankheijden.insights.listeners.PistonListener.handlePistonBlock(PistonListener.java:101) ~[Insights-6.13.0.jar:?]
        at dev.frankheijden.insights.listeners.PistonListener.handlePistonEvent(PistonListener.java:59) ~[Insights-6.13.0.jar:?]
        at dev.frankheijden.insights.listeners.PistonListener.onBlockPistonRetract(PistonListener.java:43) ~[Insights-6.13.0.jar:?]
        at com.destroystokyo.paper.event.executor.asm.generated.GeneratedEventExecutor961.execute(Unknown Source) ~[?:?]
        at org.bukkit.plugin.EventExecutor$2.execute(EventExecutor.java:77) ~[paper-api-1.19.2-R0.1-SNAPSHOT.jar:?]
        at co.aikar.timings.TimedEventExecutor.execute(TimedEventExecutor.java:80) ~[paper-api-1.19.2-R0.1-SNAPSHOT.jar:git-Paper-300]
        at org.bukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java:70) ~[paper-api-1.19.2-R0.1-SNAPSHOT.jar:?]
        at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:670) ~[paper-api-1.19.2-R0.1-SNAPSHOT.jar:?]
        at net.minecraft.world.level.block.piston.PistonBaseBlock.moveBlocks(PistonBaseBlock.java:393) ~[?:?]
        at net.minecraft.world.level.block.piston.PistonBaseBlock.triggerEvent(PistonBaseBlock.java:270) ~[?:?]
        at net.minecraft.world.level.block.state.BlockBehaviour$BlockStateBase.triggerEvent(BlockBehaviour.java:969) ~[?:?]
        at net.minecraft.server.level.ServerLevel.doBlockEvent(ServerLevel.java:1811) ~[?:?]
        at net.minecraft.server.level.ServerLevel.runBlockEvents(ServerLevel.java:1797) ~[?:?]
        at net.minecraft.server.level.ServerLevel.tick(ServerLevel.java:690) ~[?:?]
        at net.minecraft.server.MinecraftServer.tickChildren(MinecraftServer.java:1535) ~[paper-1.19.2.jar:git-Paper-300]
        at net.minecraft.server.dedicated.DedicatedServer.tickChildren(DedicatedServer.java:446) ~[paper-1.19.2.jar:git-Paper-300]
        at net.minecraft.server.MinecraftServer.tickServer(MinecraftServer.java:1397) ~[paper-1.19.2.jar:git-Paper-300]
        at net.minecraft.server.MinecraftServer.runServer(MinecraftServer.java:1173) ~[paper-1.19.2.jar:git-Paper-300]
        at net.minecraft.server.MinecraftServer.lambda$spin$0(MinecraftServer.java:305) ~[paper-1.19.2.jar:git-Paper-300]
        at java.lang.Thread.run(Thread.java:833) ~[?:?]`

Insights 6.13.0 - LandsAddon don't work on new Lands plugin versions
Lands are scan to infinity and never give back information about blocks in land!

**Comment by FrankHeijden** [comment] 2023-12-11 12:49
Duplicate of #184

**Closed by FrankHeijden** 2023-12-11 12:49 UTC
